travis:
  secure:
    BINSTAR_TOKEN: m8fifD5mi70fnLBuXcYvq3CiEwKzVDhCEcM2M3mbvGQWJmZB8TfNI5F/wEQtCDu/YQ6wMeo05UlcRi0ng0cdOeB21vwUze2ko1MCjIMN2WgHSD1z7cVdtq9Dkf1MFbBLay0wXjAtHyPwvQVWUXyOJaSWDjqqqEq8RyDcytCxD1S2WlFxxdP2BLK1DtzDc0XDcXfPC9edAiy+TzxPOEvtoK1ZpkyuQ7cr8McQ5+fOCrDYvYau0yJmUyDPXL+YBAKVagVkI7bSAb41UlMB4IAq6gaCfsPLVdH4DdWYoXeUkT+aQZXOTQ+Zy4ukHjYLBDE+sn3S0RRC6OBT5YVONG11W6rmZJTDPqtf+emwRFBLi0/jdEUZSdDIW2QZkb/gA6cRxoDsOCU+WNkSJQFYwELyk7/btunn1YgQQdMyCZPdyiCqsIaX+zhf/AQgNXUIIe/dafkEUMaBHETmtuXAhrg8oJ67xLwyM7AMTAg9DS9QcDnNjMJ9Lv40T57eAZLzMw0dvmBIXuGSNPvuy45CEA8m78q0iOsjn6IEpfOgUWOa/WaByL6tujEqV8Dow2pBZe0h3cSHlQ+p/WrbRn2Eq2QAJg0NyaW6QulPlxLF5WoA6iPm5gfFWTi+83i2Qvyth/EofBlzYA4rLDjrrPhKAy2Oxho5PYqMAWuaR5eU84BU/hA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
